language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.6"


before_install:
  - pip install --upgrade virtualenv
  - virtualenv --python=python venv
  - source venv/bin/activate
  - python --version
  - pip --version
  - pip install nose python-coveralls flake8

install:
  - pip install -e ./

script:
  - nosetests --with-coverage --cover-erase --cover-package=dtw -v -w tests/

after_success:
    - coveralls
    - flake8 --statistics --count --config=setup.cfg dtw
    - pip uninstall -y dtw

after_failure:
    - pip uninstall -y dtw
